--- #YAML:1.0
name:               XML-Compile-SOAP-WSA
version:            0.12
abstract:           SOAP Web Service Addressing
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:       0
    File::Spec:           0
    Log::Report:          0.28
    Test::More:           0.54
    XML::Compile:         1.16
    XML::Compile::Cache:  0.96
    XML::Compile::SOAP:   2.18
    XML::Compile::Tester:  0.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
